### ISSUE TITLE
Omega Edit reports create session error when opening a file on Windows 10

### ISSUE THREAD

**Issue by rt320** [ctc-oss/daffodil-vscode#68]
Omega Edit reports create session error when opening a file on Windows 10.
Steps to re-create:
open vscode with code from ctc repository commit https://github.com/ctc-oss/daffodil-vscode/commit/e1690e7f1a3c06b5cbaf3b3b1510fc610a3a98c3.
Run extension in debug.
In the new debug window open pallet and choose OmegaEdit: Data Editor (WIP).
Select any file in the popup window.
The editor opens with the message "create session error". The error may have something to do with path separation symbols in Windows vs MAC/Linux

The following error message is displayed in the terminal window:
gRPC server bound to: /127.0.0.1:9000
[ERROR] [05/10/2022 10:39:56.507] [omega-grpc-akka.actor.internal-dispatcher-3] [akka://omega-grpc/user/$a] Failed to load OmegaEdit native library from 0.8.3/windows_64/omega_edit.dll
java.lang.RuntimeException: Failed to load OmegaEdit native library from 0.8.3/windows_64/omega_edit.dll
        at com.ctc.omega_edit.FFI$.liftedTree1$1(FFI.scala:92)
        at com.ctc.omega_edit.FFI$.i$lzycompute(FFI.scala:75)
        at com.ctc.omega_edit.FFI$.i(FFI.scala:70)
        at com.ctc.omega_edit.api.OmegaEdit$.newSessionCb(OmegaEdit.scala:36)
        at com.ctc.omega_edit.grpc.Editors$.com$ctc$omega_edit$grpc$Editors$$sessionFor(Editors.scala:64)
        at com.ctc.omega_edit.grpc.Editors$$anonfun$receive$1.applyOrElse(Editors.scala:81)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at com.ctc.omega_edit.grpc.Editors.aroundReceive(Editors.scala:67)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.nio.file.Files.copy(Files.java:3112)
        at com.ctc.omega_edit.FFI$.liftedTree1$1(FFI.scala:84)
        ... 18 more

[ERROR] [05/10/2022 10:40:59.105] [omega-grpc-akka.actor.default-dispatcher-5] [akka.grpc.scaladsl.GrpcExceptionHandler(akka://omega-grpc)] Unhandled error: [Ask timed out on [Actor[akka://omega-grpc/user/$a#1326715070]] after [1000 ms]. Message of type [com.ctc.omega_edit.grpc.Editors$Create]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.] (akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://omega-grpc/user/$a#1326715070]] after [1000 ms]. Message of type [com.ctc.omega_edit.grpc.Editors$Create]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.)
[ERROR] [05/10/2022 10:42:23.547] [omega-grpc-akka.actor.internal-dispatcher-2] [akka://omega-grpc/user/$a] Failed to load OmegaEdit native library from 0.8.3/windows_64/omega_edit.dll
java.lang.RuntimeException: Failed to load OmegaEdit native library from 0.8.3/windows_64/omega_edit.dll
        at com.ctc.omega_edit.FFI$.liftedTree1$1(FFI.scala:92)
        at com.ctc.omega_edit.FFI$.i$lzycompute(FFI.scala:75)
        at com.ctc.omega_edit.FFI$.i(FFI.scala:70)
        at com.ctc.omega_edit.api.OmegaEdit$.newSessionCb(OmegaEdit.scala:36)
        at com.ctc.omega_edit.grpc.Editors$.com$ctc$omega_edit$grpc$Editors$$sessionFor(Editors.scala:64)
        at com.ctc.omega_edit.grpc.Editors$$anonfun$receive$1.applyOrElse(Editors.scala:81)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at com.ctc.omega_edit.grpc.Editors.aroundReceive(Editors.scala:67)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.nio.file.Files.copy(Files.java:3112)
        at com.ctc.omega_edit.FFI$.liftedTree1$1(FFI.scala:84)
        ... 18 more

[ERROR] [05/10/2022 10:42:24.549] [omega-grpc-akka.actor.default-dispatcher-6] [akka.grpc.scaladsl.GrpcExceptionHandler(akka://omega-grpc)] Unhandled error: [Ask timed out on [Actor[akka://omega-grpc/user/$a#1326715070]] after [1000 ms]. Message of type [com.ctc.omega_edit.grpc.Editors$Create]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.] (akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://omega-grpc/user/$a#1326715070]] after [1000 ms]. Message of type [com.ctc.omega_edit.grpc.Editors$Create]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
![Win10OmegaEditError](https://user-images.githubusercontent.com/98881959/167658121-40248936-aae1-417b-9621-cb9bb0e372b2.PNG)
)

**Comment by Shanedell** [comment]
@rt320 Can you re checkout the `init-viewport-editing` PR and make sure that code is pulled down. The version of the omega-edit server you are using the issue. You are currently trying to use `0.8.3` the latest is `0.9.7` which has fixes the fixed the missing windows native library file
